#' Xplore_database
#' @export
xplore_database <- setClass("Xplore",
                            slots = c(
                                # from tabular output
                                ConvergenceData = "data.frame",
                                Doses           = "data.frame",
                                EtaCovariate    = "data.frame",
                                EtaCovariateCat = "data.frame",
                                EtaStacked      = "data.frame",
                                NonParEta       = "data.frame",
                                NonParOverall   = "data.frame",
                                NonParStacked   = "data.frame",
                                NonParSupport   = "data.frame",
                                Omega           = "data.frame",
                                OmegaStderr     = "data.frame",
                                Residuals       = "data.frame",
                                Secondary       = "data.frame",
                                StrCovariate    = "data.frame",
                                StrCovariateCat = "data.frame",
                                Theta           = "data.frame",
                                ThetaCovariance = "data.frame",
                                VarCovar        = "data.frame",
                                Notes           = "character",
                                ObsName         = "character",
                                ObsUnits        = "character",
                                # from dmp.txt
                                coefficients   = "list",
                                logLik          = "numeric",
                                nObs            = "numeric",
                                nSubj           = "numeric",
                                nParm           = "numeric",
                                returnCode      = "numeric",
                                omega           = "matrix",
                                method          = "character",
                                varFix          = "matrix",
                                Covariance      = "matrix",
                                Correlation     = "matrix",
                                Inverse         = "matrix",
                                idTable         = "data.frame",
                                residuals       = "data.frame",
                                test.mdl        = "character",
                                cols1.txt       = "character"
                            )
)
